#
# Expected repository setup
#
# 1. Pages is enabled and tracking a branch that does not contain anything
# 2. The `github-pages` environment has been created and is protected (either via the "Selected branches" or "Protected branches" options)
# 3. The repository is an actor on this feature flag: https://admin.github.com/devtools/feature_flags/pages_preview_deployments
#

#
# Triggers
# Note: for public repositories accepting forks, pull_request_target is the only safe trigger.
#
on:
  pull_request:

# Required: Pages permissions
permissions:
  contents: read
  pages: write
  id-token: write

name: Build & Deploy Pages Preview

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      #
      # Required: Checkout (current branch OR head reference for PRs)
      #
      - name: Checkout PR
        # if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v2
        with:
          # For PRs make sure to checkout the PR branch
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Attempt build storybook
        run: npm run build:storybook

      #
      # Required: Pages artifacts creation
      #

      - name: Archive build output
        run: 'tar --dereference --directory storybook-static/ -cvf artifact.tar .'

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: artifact.tar

      - name: Deploy to GitHub Pages
        id: deployment
        uses: paper-spa/deploy-pages@main
        with:
          preview: true
